version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/frontend/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "/backend/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
