version: "3"

services:
  frontend:
    build:
      context: frontend/
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - sqlite-data:${SQLITE_FILE_NAME}

  backend:
    build:
      context: backend/
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-letsencrypt
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
