name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r frontend/requirements.txt
    - name: Run Tests
      run: |
        cd frontend
        python manage.py test
